apiVersion: v1
description: Mojaloop Helm chart for Kubernetes
name: mojaloop
version: 10.1.0
appVersion: "ml-api-adapter: v10.1.1; central-ledger: v10.1.0; account-lookup-service: v10.1.0; quoting-service: v10.1.0; central-settlement: v9.5.0; central-event-processor: v9.5.0; bulk-api-adapter: v9.2.0-snapshot; email-notifier: v9.5.0; simulator: v9.4.0; als-oracle-pathfinder: v8.7.1; transaction-requests-service: v9.3.0; finance-portal: v9.2.0; finance-portal-settlement-management: v9.2.0"
home: http://mojaloop.io
icon: http://mojaloop.io/images/logo.png
sources:
  - https://github.com/mojaloop/mojaloop
  - https://github.com/mojaloop/helm
maintainers:
  - name: Miguel de Barros
    email: miguel.debarros@modusbox.com
