apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "reportingservice.fullname" . }}-config
  labels:
    app.kubernetes.io/name: {{ include "reportingservice.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
data:
  default.json: {{ (tpl (.Files.Get "configs/default.json") . ) | quote }}
  {{- if .Values.rules }}
  {{- if (typeIs "string" .Values.rules) }}
  rules.json: {{ .Values.rules | quote }}
  {{- else }}
  rules.json: {{ .Values.rules | toPrettyJson | quote }}
  {{- end }}
  {{- else }}
  rules.json: "[]"
  {{- end }}

{{- if .Values.sidecar.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "reportingservice.fullname" . }}-sidecar
  labels:
    app.kubernetes.io/name: {{ include "reportingservice.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
data:
  default.json: {{ (tpl (.Files.Get "configs/default-sidecar.json") . ) | quote }}
{{- end }}
