{{- $dbHost := ( .Values.config.db_host | replace "$release_name" .Release.Name ) -}}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "reportingservice.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "reportingservice.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "reportingservice.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "reportingservice.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/version: {{ .Chart.AppVersion }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    spec:
{{- if .Values.affinity }}
      affinity:
{{ toYaml .Values.affinity | indent 8 }}
{{- end }}
{{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
{{- end }}
{{- if .Values.tolerations }}
      tolerations:
{{ toYaml .Values.tolerations | indent 8 }}
{{- end }}
      {{- if .Values.init.enabled }}
      initContainers:
        {{- if eq .Values.config.db_type "mysql"}}
        - name: {{ .Values.init.mysql.name }}
          image: {{ .Values.init.mysql.repository }}:{{ .Values.init.mysql.tag }}
          imagePullPolicy: {{ .Values.init.mysql.pullPolicy }}
          command:
            - sh
            - "-c"
            - {{ (.Values.init.mysql.command | replace "$db_user" (print .Values.config.db_user) | replace "$db_password" (print .Values.config.db_password) | replace "$db_host" $dbHost | replace "$db_database" (print .Values.config.db_database) | replace "$db_port" (print .Values.config.db_port) )| quote }}
        {{- end }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
          {{- range $port := .Values.service.ports }}
            - name: {{ $port.name }}
              containerPort: {{ $port.internalPort }}
          {{- end }}
          {{- if .Values.readinessProbe.enabled }}
          readinessProbe:
            httpGet:
              path: {{ .Values.readinessProbe.httpGet.path }}
              port: {{ .Values.service.ports.api.internalPort }}
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
          {{- end }}
          {{- if .Values.livenessProbe.enabled }}
          livenessProbe:
            httpGet:
              path: {{ .Values.livenessProbe.httpGet.path }}
              port: {{ .Values.service.ports.api.internalPort }}
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
          {{- end }}
          env:
            - name: DB_HOST
              value: {{ $dbHost }}
            - name: DB_USER
              value: {{ .Values.config.db_user | quote}}
            - name: DB_PASSWORD
              value: {{ .Values.config.db_password | quote}}
            - name: DB_DATABASE
              value: {{ .Values.config.db_database | quote }}
          volumeMounts:
          - name: {{ template "reportingservice.fullname" . }}-config-volume
            mountPath: /opt/reporting-service/config
          {{- if .Values.config.endpointSecurity.jwsSign }}
          - name: jws-signing-key
            mountPath: /opt/reporting-service/secrets
          {{- end }}
        {{- if .Values.sidecar.enabled }}
        - name: {{ .Chart.Name }}-sidecar
          image: "{{ .Values.sidecar.image.repository }}:{{ .Values.sidecar.image.tag }}"
          imagePullPolicy: {{ .Values.sidecar.image.pullPolicy }}
          {{- if .Values.sidecar.image.imagePullSecrets }}
          imagePullSecrets:
          {{ toYaml .Values.sidecar.image.imagePullSecrets | indent 10 }}
          {{- end }}
          command: {{ .Values.sidecar.image.command }}
          ports:
            - containerPort: {{ .Values.sidecar.service.internalPort }}
          {{- if .Values.sidecar.readinessProbe.enabled }}
          readinessProbe:
            httpGet:
              path: {{ .Values.sidecar.readinessProbe.httpGet.path }}
              port: {{ .Values.sidecar.service.internalPort }}
            initialDelaySeconds: {{ .Values.sidecar.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.sidecar.readinessProbe.periodSeconds }}
          {{- end }}
          {{- if .Values.sidecar.livenessProbe.enabled }}
          livenessProbe:
            httpGet:
              path: {{ .Values.sidecar.livenessProbe.httpGet.path }}
              port: {{ .Values.sidecar.service.internalPort }}
            initialDelaySeconds: {{ .Values.sidecar.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.sidecar.livenessProbe.periodSeconds }}
          {{- end }}
          volumeMounts:
            - name: {{ template "reportingservice.fullname" . }}-sidecar-volume
              mountPath: /opt/event-sidecar/config
          env:
            - name: LOG_LEVEL
              value: {{ .Values.sidecar.config.log_level }}
        {{- end }}
      volumes:
        {{- if .Values.config.endpointSecurity.jwsSign }}
        - name: jws-signing-key
          secret:
            secretName: {{ template "reportingservice.fullname" . }}-jws-signing-key
        {{- end }}
        - name: {{ template "reportingservice.fullname" . }}-config-volume
          configMap:
            name: {{ template "reportingservice.fullname" . }}-config
            items:
            - key: default.json
              path: default.json
            - key: rules.json
              path: rules.json
        {{- if .Values.sidecar.enabled }}
        - name: {{ template "reportingservice.fullname" . }}-sidecar-volume
          configMap:
            name: {{ template "reportingservice.fullname" . }}-sidecar
            items:
            - key: default.json
              path: default.json
        {{- end }}
